title:            Tw93
description:      "Hi，我是 Tw93，是一个前端工程师，会一点 Swift / Rust / Python，喜欢折腾各种新技术。"

github: tw93
weibo: tw1118
zhihu: tw93
zhuanlan: tw1993
disqus_shortname: tw93

url: https://tw93.fun
menu:
  - title: 'Categories'
    url: '/categories.html'
  - title: 'About'
    url: '/about'
  - title: 'Github'
    url: 'https://github.com/tw93'
  - title: 'RSS'
    url: '/feed.xml'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html
assetUrl: //tw93.fun/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==



google_analytics: UA-57207999-1
baidu_verify: kxGpkpWG7G
google_verify: DbapjTyfmMvvmkuA1GiGcXMqgPQrtgxeUTGY-MrEOYw

paginate: 7
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: true
payImage: //gw.alicdn.com/imgextra/i2/O1CN01KuF4gz1jjWL0l4V0P_!!6000000004584-0-tps-1152-1152.jpg

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

plugins: [jekyll-paginate]
