title:            Tw93
description:      Describe your website here.

# put your disqus here
disqus_shortname: tw93
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:              # logo visible in the topbar
excerpt_separator: <!--more-->

url: http://tw93.github.io
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/tw93"
  - title: "weibo"
    url: "http://weibo.com/2218703493/profile?topnav=1&wvr=6"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-57207999-1
google_verify:
bing_verify:

timezone:    Asia/Shanghai
locale:      zh_CN
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: cosy-jekyll-theme
