title:            Tw93
description:      "Tw93 前端 javascript css html weex react 代码 编程 知乎"

disqus_shortname: tw93

#social
github: tw93
weibo: tw1118
zhihu: tw93
zhuanlan: tw1993

url: http://tw93.github.io
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'

# Background image to be tiled on all pages
background:

# Analytics
google_analytics: UA-57207999-1

timezone:    Asia/Shanghai
locale:      zh_CN
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

# Octopress
# Default extensions
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: cosy-jekyll-theme
