title:            Tw93
description:      "Tw93 前端 javascript css html weex react 代码 编程 知乎"

# put your disqus here
disqus_shortname: tw93
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:              # logo visible in the topbar
excerpt_separator: <!--more-->

#social
github: tw93
zhihu: tw93
weibo: tw1118

url: http://tw93.github.io
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-57207999-1
google_verify:
bing_verify:

timezone:    Asia/Shanghai
locale:      zh_CN
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 5

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: cosy-jekyll-theme
