title:            Tw93
description:      "这里是Tw93的技术博客，用于我的学习总结和研究，主要方向是前端，热爱分享、开源，最近在使用react和weex。"

github: tw93
weibo: tw1118
zhihu: tw93
zhuanlan: tw1993
disqus_shortname: tw93

url: //tw93.github.io
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html
assetUrl: http://7vihmc.com1.z0.glb.clouddn.com/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==



google_analytics: UA-57207999-1
baidu_verify: kxGpkpWG7G
google_verify: DbapjTyfmMvvmkuA1GiGcXMqgPQrtgxeUTGY-MrEOYw

paginate: 6
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: true
payImage: WechatIMG1.jpeg?imageslim

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-minify-html


html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false

theme: cosy-jekyll-theme
