title:            Tw93
description:      "这里是Tw93的技术博客，用于我的学习总结和研究，主要方向是前端，热爱分享、开源，最近在使用react和weex。"

disqus_shortname: tw93

#social
github: tw93
weibo: tw1118
zhihu: tw93
zhuanlan: tw1993

url: //tw93.github.io
menu:
  - title: 'Categories'
    url: '/categories'
  - title: 'About'
    url: '/about'

# Background image to be tiled on all pages
background:

# Analytics
google_analytics: UA-57207999-1

timezone:    Asia/Shanghai
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html

# Amount of post to show on home page
paginate: 6

# Octopress
# Default extensions
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

assetUrl: http://7vihmc.com1.z0.glb.clouddn.com/

showBuyCoffee: true
payImage: WechatIMG1.jpeg?imageslim

baidu_verify: kxGpkpWG7G
google_verify: DbapjTyfmMvvmkuA1GiGcXMqgPQrtgxeUTGY-MrEOYw


include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "package.json", "node_modules"]
gems: [jekyll-paginate,jekyll-sitemap]
theme: cosy-jekyll-theme
